dist: xenial

language: go

go:
  - 1.12.x

go_import_path: github.com/appsody/appsody-operator

services:
  - docker

install:
  - export RELEASE_VERSION=v0.9.0
  - wget https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
  - chmod +x operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
  - sudo cp operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu /usr/local/bin/operator-sdk
  - rm operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
  - export GO111MODULE=on

  - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - tar xvf openshift-origin-client-tools*.tar.gz

  - export PATH="$(pwd)":$PATH
  - oc version
  - oc cluster up
  



script: 
  - operator-sdk build appsody-operator

# install-minishift: 
#   - install-minishift.sh
#   - export PATH=$PATH:/minishift/


# jobs:
#  include:
#    - name: unit test

