language: go

go:
  - 1.12.x

go_import_path: github.com/appsody/appsody-operator

services:
  - docker

install:
  - export $RELEASE_VERSION=v0.9.0
  - wget https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
  - chmod +x operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
  - cp operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu /usr/local/bin/operator-sdk
  - rm operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu

script: skip

#  - operator-sdk build appsody-operator

# install-minishift: 
#  - install-minishift.sh
#  - export PATH=$PATH:/minishift/


# jobs:
#  include:
#    - name: unit test

